# Performing Principal Component Analysis (PCA) - Lab

## Introduction

Now that you have high level overview of PCA as well as some of the details in the algorithm itself, its time to practice implementing PCA on your own using the NumPy package. 

## Objectives

You will be able to:
    
* Implement PCA from scratch using NumPy

## Import the Data

To start, import the data stored in the file 'foodusa.csv'.

In [2]:
import numpy as np
from numpy import array
from numpy.linalg import eig, inv
import pandas as pd#Your code here

In [9]:
df = pd.read_csv('foodusa.csv', index_col=0)
df.head()

Bread  Burger  Milk  Oranges  Tomatoes
City                                             
ATLANTA     24.5    94.5  73.9     80.1      41.6
BALTIMORE   26.5    91.0  67.5     74.6      53.3
BOSTON      29.7   100.8  61.4    104.0      59.6
BUFFALO     22.8    86.6  65.3    118.4      51.2
CHICAGO     26.7    86.7  62.7    105.9      51.2

## Normalize the Data

Next, normalize your data by subtracting the feature mean from each of the columns

In [10]:
mean = df.mean()
df = df - mean#Your code here

## Calculate the Covariance Matrix

The next step for PCA is to calculate to covariance matrix for your normalized data. Do so here.

In [11]:
cov = np.cov([df.Bread, df.Burger, df.Milk, df.Oranges, df.Tomatoes])#Your code here

In [12]:
cov

array([[  6.2844664 ,  12.91096838,   5.71905138,   1.31037549,
          7.28513834],
       [ 12.91096838,  57.07711462,  17.50752964,  22.69187747,
         36.29478261],
       [  5.71905138,  17.50752964,  48.30588933,  -0.27503953,
         13.44347826],
       [  1.31037549,  22.69187747,  -0.27503953, 202.75628458,
         38.76241107],
       [  7.28513834,  36.29478261,  13.44347826,  38.76241107,
         57.80055336]])

## Calculate the Eigenvectors

Next, calculate the eigenvectors for your covariance matrix.

In [14]:
eig_val, eig_vec = np.linalg.eig(cov)
eig_vec#Your code here

array([[-0.02848905, -0.16532108, -0.96716354, -0.18972574,  0.02135748],
       [-0.2001224 , -0.63218494,  0.24877074, -0.65862454,  0.25420475],
       [-0.0416723 , -0.44215032,  0.03606094,  0.10765906, -0.88874949],
       [-0.93885906,  0.31435473, -0.01521357, -0.06904699, -0.12135003],
       [-0.27558389, -0.52791603, -0.03429221,  0.71684022,  0.36100184]])

## Sorting the Eigenvectors to Determine Primary Components

Great! Now that you have the eigenvectors and their associated eigenvalues, sort the eigenvectors based on their eigenvalues!

In [16]:
eig_indeces = np.argsort(eig_val)[::-1]
eig_sort = eig_vec[:,eig_indeces]
eig_sort#Your code here

array([[-0.02848905, -0.16532108,  0.02135748, -0.18972574, -0.96716354],
       [-0.2001224 , -0.63218494,  0.25420475, -0.65862454,  0.24877074],
       [-0.0416723 , -0.44215032, -0.88874949,  0.10765906,  0.03606094],
       [-0.93885906,  0.31435473, -0.12135003, -0.06904699, -0.01521357],
       [-0.27558389, -0.52791603,  0.36100184,  0.71684022, -0.03429221]])

## Reprojecting the Data

Finally, reproject the dataset using your eigenvectors. Reproject the dataset down to 2 dimensions.

In [18]:
transformed = eig_sort.dot(df.T).T
transformed[:2]#Your code here

array([[ 11.10636706,  14.73134932, -14.17203836,   1.85530932,
        -13.15196933],
       [  1.21900301,  21.44989411,  -7.19007196,  -0.14425049,
        -18.50968283]])

## Summary

Well done! You've now coded PCA on your own using NumPy! With that, it's time to look at further application of PCA.