# Vectors and Matrices in Numpy - Lab

## Introduction

In this lab, you'll solve some simple matrix creation and manipulation exercises based on what you've learned so far in this section. The key takeaway here is to be able to understand how to use indexing with matrices and vectors while applying some basic operations.

## Objectives
You will be able to:
* Define vectors and matrices in NumPy
* Check the shape of vectors and matrices
* Access and manipulate individual scalar components of a matrix. 

## 1. Define two arrays $A$  with shape $ (4 \times 2)$ and $B$ with shape $(2 \times 3)$ 
So    $A =    
  \left[ {\begin{array}{cc}
   1402 & 191 \\
   1371 &  821\\
   949 &  1437 \\
   147 & 1448 \\
  \end{array} }\right]
$
and
$
B =    
  \left[ {\begin{array}{ccc}
   1 & 2 & 3 \\
   4 & 5 & 6\\
  \end{array} }\right]
$

In [2]:
import numpy as np
A = np.array([[1402, 191],[1371,821],[949,1437],[147,1448]])
B = np.array([[1,2,3],[4,5,6]])
print(A)
print(B)# Code Here

[[1402  191]
 [1371  821]
 [ 949 1437]
 [ 147 1448]]
[[1 2 3]
 [4 5 6]]


## 2. Print the dimensions of $A$ and $B$ 

In [4]:
print(A.shape)
print(B.shape)# Code Here

(4, 2)
(2, 3)


## 3. Print some of the elements from $A$: 
* first row and first column
* first row and second column
* third row and second column
* fourth row and first column

In [6]:
print(A[0,0])
print(A[0,1])
print(A[2,1])
print(A[3,0])

1402
191
1437
147


In [53]:
# Code Here

1402
191
1437
147


## 4. Write a routine to populate a matrix with random data
* Create an $(3 \times 3)$ Numpy array with all zeros (use `np.zeros()`)
* Access each location $(i,j)$ of this matrix and fill in random values between the range 1 and 10. 

In [54]:
R = np.zeros(3,3)# Code Here (due to random data , your output might be different)

before random data:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

after random data:
 [[2. 7. 5.]
 [7. 9. 3.]
 [6. 5. 9.]]


In [20]:
R = np.zeros((3,3))
import random
for x in range(0, R.shape[0]):
               for y in range(0, R.shape[1]):
                   R[x][y] = random.randrange(1,10)

In [21]:
R

array([[6., 2., 2.],
       [4., 1., 1.],
       [3., 6., 2.]])

## 5. Turn the above routine into a function
* Create two $(4 \times 4)$ zero valued matrices and fill with random data using the function
* Add the matrices together in numpy 
* Show the results

In [23]:
def fillrnd(shape1, shape2):
    R = np.zeros((shape1,shape2))

    for x in range(0, R.shape[0]):
                   for y in range(0, R.shape[1]):
                       R[x][y] = random.randrange(1,10)
    return R

X = fillrnd(4,4)
Y= fillrnd(4,4)

print(X)
print(Y)
X+Y    # Code Here (due to random data , your output might be different)

[[7. 9. 4. 9.]
 [7. 8. 4. 9.]
 [3. 8. 1. 8.]
 [8. 1. 5. 9.]]
[[6. 8. 5. 6.]
 [4. 1. 6. 2.]
 [9. 3. 7. 7.]
 [6. 3. 4. 2.]]


array([[13., 17.,  9., 15.],
       [11.,  9., 10., 11.],
       [12., 11.,  8., 15.],
       [14.,  4.,  9., 11.]])

## Summary 

In this lab, we saw how to create and manipulate vectors and matrices in numpy. We shall now move forward to learning more complex operations including dot products and inverses. 