# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [34]:
import numpy as np

A = np.array([[7,3,6],[5,6,9]])
B = np.array([[6,2,7],[9,0,9],[1,7,9]])
C = np.array([[8,7,8],[4,7,8],[1,1,3]])# Your code here

In [35]:
A.dot(B+C) == (A.dot(B)+A.dot(C))

array([[ True,  True,  True],
       [ True,  True,  True]])

## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [43]:
A = np.array([[7,3],[5,6],[8,8]])
B = np.array([[6,9],[3,9]])
C = np.array([[8],[4]])

In [44]:
A.dot(B.dot(C)) == (A.dot(B)).dot(C)# Your code here 

array([[ True],
       [ True],
       [ True]])

## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [48]:
A = np.array([[7,3],[5,6],[8,8]])
B = np.array([[6,9,5],[3,9,2]])

In [49]:
A.dot(B) != B.dot(A)# Your code here 

/Users/Allie/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


True

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [54]:
A = np.array([[7,3,5],[5,6,3],[8,8,2]])
B = np.array([6,9,5])

In [55]:
A.T.dot(B) == B.T.dot(A)# Your code here 

array([ True,  True,  True])

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [59]:
A = np.array([[7,3,5],[5,6,3],[8,8,2]])
B = np.array([[6,9,5],[9,3,5],[0,7,3]])

In [60]:
(A.dot(B).T) == B.T.dot(A.T)# Your code here 

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 